sudo: requried
services:
  - docker

before_install:
  - docker build -t loserforever/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run loserforever/react-test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t loserforever/multi-client ./client
  - docker build -t loserforever/multi-nginx ./nginx
  - docker build -t loserforever/multi-server ./server
  - docker build -t loserforever/multi-worker ./worker
  # Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push loserforever/multi-client
  - docker push loserforever/multi-nginx
  - docker push loserforever/multi-server
  - docker push loserforever/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multidocker
  env: multidocker-env2
  bucket_name: elasticbeanstalk-ap-southeast-1-149101267308
  bucker_path: multidocker
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
