version: '3.8'

services:
  nginx:
    restart: always
    image: loserforever/multi-nginx
    ports:
      - '80:80'
  api:
    image: loserforever/multi-server
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
  client:
    image: loserforever/multi-client
  worker:
    image: loserforever/multi-worker
    environment:
      - REDIS_HOST
      - REDIS_PORT