apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            # - name: POSTGRES_DB
            #   valueFrom:
            #     configMapKeyRef:
            #       name: env-configmap
            #       key: pg_database
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: env-secret
            #       key: pg_user
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: env-secret
            #       key: pg_password

            - name: POSTGRES_DB
              value: fibvalues
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgress
